/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Credentials.Credentials;
import Model.Hospital.Hospital;
import Model.System.DatabaseConnection;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author shubham
 */
public class CreateHospitalPanel extends javax.swing.JPanel {

    Logger logger = LogManager.getLogger(CreateHospitalPanel.class);
    DatabaseConnection db = new DatabaseConnection();
    Long hospId;

    /**
     * Creates new form ManageDoctorsPanel
     */
    public CreateHospitalPanel() {
        initComponents();
        hospId = (long) (Math.random() * (9999 - 1) + 1);
        hospID.setText(String.valueOf(hospId));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        hospID = new javax.swing.JTextField();
        hospName = new javax.swing.JTextField();
        createHospBtn = new javax.swing.JButton();
        hospAdminUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hospAdminPwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hospCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 118, 211));
        jLabel2.setText("Hospital ID");

        hospID.setEditable(false);
        hospID.setBackground(null);
        hospID.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        hospID.setForeground(new java.awt.Color(25, 118, 211));

        hospName.setBackground(null);
        hospName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        hospName.setForeground(new java.awt.Color(25, 118, 211));

        createHospBtn.setBackground(new java.awt.Color(25, 118, 211));
        createHospBtn.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        createHospBtn.setForeground(new java.awt.Color(255, 255, 255));
        createHospBtn.setText("Create Hospital");
        createHospBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createHospBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHospBtnActionPerformed(evt);
            }
        });

        hospAdminUserName.setBackground(null);
        hospAdminUserName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        hospAdminUserName.setForeground(new java.awt.Color(25, 118, 211));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 118, 211));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Hospital Panel");

        hospAdminPwd.setBackground(null);
        hospAdminPwd.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        hospAdminPwd.setForeground(new java.awt.Color(25, 118, 211));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 118, 211));
        jLabel4.setText("Hospital Name");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 118, 211));
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 118, 211));
        jLabel8.setText("Username");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 118, 211));
        jLabel5.setText("Hospital City");

        hospCity.setBackground(null);
        hospCity.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        hospCity.setForeground(new java.awt.Color(25, 118, 211));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 118, 211));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hospital Admin Credentials");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hospAdminUserName)
                            .addComponent(hospAdminPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(createHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hospAdminPwd, hospAdminUserName, hospCity, hospID, hospName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hospID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(hospCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hospAdminUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hospAdminPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(createHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hospAdminPwd, hospAdminUserName, hospCity, hospID, hospName});

    }// </editor-fold>//GEN-END:initComponents


    private void createHospBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHospBtnActionPerformed
        // TODO add your handling code here:
        if (hospName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter valid input!");
            return;
        }

        if (Pattern.matches("^[0-9]*$", hospName.getText())) {
            JOptionPane.showMessageDialog(this, "Name cannot contain numbers!");
            return;
        }

        if (hospCity.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter valid input!");
            return;
        }

        if (Pattern.matches("^[0-9]*$", hospCity.getText())) {
            JOptionPane.showMessageDialog(this, "Name cannot contain numbers!");
            return;
        }

        if (hospAdminUserName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter hospital admin username!");
            return;
        }

        if (String.valueOf(hospAdminPwd.getPassword()).trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter hospital admin passwords!");
            return;
        }

        int pwdLen = hospAdminPwd.getPassword().length;
        if (pwdLen < 6) {
            JOptionPane.showMessageDialog(this, "Password should be minimum 6 characters!");
            return;
        }

        Connection dbConn = null;
        PreparedStatement docStatement = null;
        PreparedStatement userStatement = null;

        Long userId = (long) (Math.random() * (9999 - 1) + 1);
        String hospQuery = "INSERT INTO project.hospital VALUES  (?, ?, ?);";
        String userQuery = "INSERT INTO project.credentials VALUES (?, ?, ?, ?, ?);";

        Hospital hosp = new Hospital();
        hosp.setHospitalId(hospId);
        hosp.setHospitalName(hospName.getText());
        hosp.setHospitalCity(hospCity.getText());

        Credentials creds = new Credentials();
        creds.setUserId(userId);
        creds.setUsername(hospAdminUserName.getText());
        creds.setPassword(String.valueOf(hospAdminPwd.getPassword()));
        creds.setRole("Hospital Admin");
        creds.setLicense("license");

        try {
            dbConn = db.getConnection();
            if (dbConn != null) {
                dbConn.setAutoCommit(false);
                docStatement = dbConn.prepareStatement(hospQuery);
                userStatement = dbConn.prepareStatement(userQuery);
                docStatement.setLong(1, hosp.getHospitalId());
                docStatement.setString(2, hosp.getHospitalName());
                docStatement.setString(3, hosp.getHospitalCity());

                userStatement.setLong(1, creds.getUserId());
                userStatement.setString(2, creds.getUsername());
                userStatement.setString(3, creds.getPassword());
                userStatement.setString(4, creds.getRole());
                userStatement.setString(5, creds.getLicense());
                if ((docStatement.executeUpdate() > 0) && userStatement.executeUpdate() > 0) {
                    System.out.println("Created Hospital Successfully!");
                    JOptionPane.showMessageDialog(this, "Created Successfully");
                    dbConn.commit();
                } else {
                    System.out.println("Failed to create hospital");
                    dbConn.rollback();
                }
            } else {
                System.out.println("DB connection not connected");
            }
        } catch (SQLException sqlExp) {
            //rollback the connection
            logger.error(sqlExp.getMessage());
            sqlExp.printStackTrace();
        } catch (Exception exp) {
            logger.error(exp.getMessage());
            exp.printStackTrace();

        } finally {
            if (docStatement != null) {
                try {
                    if (!docStatement.isClosed()) {
                        docStatement.close();
                    }
                } catch (SQLException err) {
                    logger.error(err.getMessage());
                    err.printStackTrace();

                }
            }
            if (dbConn != null) {
                try {
                    if (!dbConn.isClosed()) {
                        db.closeConnection(dbConn);
                    }
                } catch (SQLException err) {
                    logger.error(err.getMessage());
                    err.printStackTrace();

                }
            }
        }
    }//GEN-LAST:event_createHospBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createHospBtn;
    private javax.swing.JPasswordField hospAdminPwd;
    private javax.swing.JTextField hospAdminUserName;
    private javax.swing.JTextField hospCity;
    private javax.swing.JTextField hospID;
    private javax.swing.JTextField hospName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
